# Generated by Django 2.2.10 on 2020-06-07 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCoach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('image', models.ImageField(blank='True', null='True', upload_to='liverpool/image')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Infocoach',
                'verbose_name_plural': 'Info sur le Coach',
            },
        ),
        migrations.CreateModel(
            name='OriginCoach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='liverpool/photo')),
                ('team', models.CharField(max_length=255)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='liverpool.InfoCoach')),
            ],
            options={
                'verbose_name': 'origin',
                'verbose_name_plural': 'Origine Coach',
            },
        ),
    ]
