# Generated by Django 2.2.10 on 2020-06-08 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liverpool', '0002_auto_20200608_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Les categories',
            },
        ),
        migrations.CreateModel(
            name='InfoJoueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('taille', models.FloatField()),
                ('poids', models.FloatField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'info joueur',
                'verbose_name_plural': 'Infos joueur',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('nom', models.CharField(max_length=255)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='liverpool.Categorie')),
                ('infojoueurs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='liverpool.InfoJoueur')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'Players',
            },
        ),
    ]
