# Generated by Django 2.2.10 on 2020-06-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liverpool', '0003_categorie_infojoueur_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infojoueur',
            name='poids',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='infojoueur',
            name='taille',
            field=models.CharField(max_length=25),
        ),
    ]
