# Generated by Django 2.2.10 on 2020-06-09 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liverpool', '0005_auto_20200608_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='infojoueurs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='liverpool.InfoJoueur'),
        ),
    ]
