# Generated by Django 2.2.10 on 2020-06-07 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'joueur',
                'verbose_name_plural': 'Info joueurs',
            },
        ),
        migrations.CreateModel(
            name='Infojoueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalite', models.CharField(max_length=200)),
                ('drapeau', models.ImageField(upload_to='home/drapeau')),
                ('position', models.CharField(max_length=200)),
                ('club', models.CharField(max_length=200)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('Joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foot', to='player.Joueur')),
            ],
            options={
                'verbose_name': 'Information joueur',
                'verbose_name_plural': 'Information des joueurs',
            },
        ),
    ]
