# Generated by Django 2.2.10 on 2020-06-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joueur',
            options={'verbose_name': 'joueur', 'verbose_name_plural': 'Nom joueurs'},
        ),
        migrations.RenameField(
            model_name='infojoueur',
            old_name='nationalite',
            new_name='nationality',
        ),
    ]
