# Generated by Django 2.2.10 on 2020-06-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20200607_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='photo',
            field=models.ImageField(default=1, upload_to='player/photo'),
            preserve_default=False,
        ),
    ]
