# Generated by Django 2.2.10 on 2020-06-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_joueur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='photo',
            field=models.ImageField(blank='True', null='True', upload_to='player/photo'),
        ),
    ]
