# Generated by Django 2.2.10 on 2020-06-07 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('image', models.ImageField(blank='True', null='True', upload_to='home/image')),
                ('isProgrammed', models.BooleanField(default=True)),
                ('score', models.IntegerField(blank='True')),
                ('date_add', models.DateTimeField()),
                ('date_upd', models.DateTimeField()),
            ],
            options={
                'verbose_name': "L'équipe A",
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.CreateModel(
            name='EquipeB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank='True', null='True', upload_to='home/equipeB/photo')),
                ('isProgrammed', models.BooleanField(default=True)),
                ('rencontre', models.DateTimeField()),
                ('lieu', models.CharField(max_length=200)),
                ('score', models.IntegerField(blank='True')),
                ('date_add', models.DateTimeField()),
                ('date_upd', models.DateTimeField()),
                ('equipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foot', to='home.EquipeA')),
            ],
            options={
                'verbose_name': "L'équipe B",
                'verbose_name_plural': 'Equipes',
            },
        ),
    ]
