# Generated by Django 2.2.10 on 2020-06-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200607_0734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipeb',
            options={'verbose_name': "L'équipes_poule_1", 'verbose_name_plural': 'Equipes_poule_2'},
        ),
    ]
