# Generated by Django 2.2.10 on 2020-06-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200607_0737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipea',
            options={'verbose_name': "L'équipe A", 'verbose_name_plural': "L'équipes_poule_A"},
        ),
        migrations.AlterModelOptions(
            name='equipeb',
            options={'verbose_name': "L'équipe A", 'verbose_name_plural': 'Equipes_poule_B'},
        ),
    ]
