# Generated by Django 2.2.10 on 2020-06-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200607_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipea',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipea',
            name='date_upd',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='equipeb',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipeb',
            name='date_upd',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
