# Generated by Django 2.2.10 on 2020-06-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200607_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipea',
            options={'verbose_name': "L'équipe A", 'verbose_name_plural': 'Equipes_poule_A'},
        ),
    ]
