# Generated by Django 2.2.10 on 2020-06-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200607_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipea',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='equipea',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='equipeb',
            name='equipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.EquipeA'),
        ),
        migrations.AlterField(
            model_name='equipeb',
            name='score',
            field=models.IntegerField(),
        ),
    ]
