# Generated by Django 2.2.10 on 2020-06-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200607_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipeb',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
