# Generated by Django 2.2.10 on 2020-06-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200607_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipeb',
            name='equipe',
        ),
    ]
